const Destination = require('../models/Destination');

const demoDestinations = [
  // === ADVENTURE (15) ===
  {
    name: 'Everest Base Camp',
    slug: 'everest-base-camp',
    category: 'Adventure',
    region: 'Eastern',
    description: 'The Everest Base Camp trek is one of the most iconic trekking routes in the world. Standing at 5,364m at the foot of Mount Everest, trekkers experience breathtaking views of the Khumbu Icefall, Sherpa culture in Namche Bazaar, and the raw beauty of the highest peaks on Earth.',
    shortDescription: 'Trek to the base of the world\'s highest mountain through stunning Himalayan landscapes.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.9, reviewCount: 342,
    priceRange: 'Rs Rs Rs', bestSeason: 'Mar-May, Sep-Nov', duration: '12-14 days', difficulty: 'Challenging',
    location: { type: 'Point', coordinates: [86.8528, 28.0025], address: 'Solukhumbu, Nepal' },
    features: ['High Altitude', 'Sherpa Culture', 'Mountain Views', 'Khumbu Glacier'],
    nearbyAttractions: ['Namche Bazaar', 'Tengboche Monastery', 'Gokyo Lakes']
  },
  {
    name: 'Annapurna Circuit',
    slug: 'annapurna-circuit',
    category: 'Adventure',
    region: 'Western',
    description: 'The Annapurna Circuit is one of the most diverse and spectacular trekking routes in the world. Circling the Annapurna massif, the trail passes through lush rice paddies, dense rhododendron forests, arid high-altitude deserts, and over the Thorong La Pass at 5,416m.',
    shortDescription: 'Epic circuit trek around the Annapurna massif with diverse landscapes and Thorong La Pass.',
    images: ['https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=1200&q=80'],
    rating: 4.8, reviewCount: 267,
    priceRange: 'Rs Rs Rs', bestSeason: 'Mar-May, Oct-Nov', duration: '15-20 days', difficulty: 'Challenging',
    location: { type: 'Point', coordinates: [83.8203, 28.5965], address: 'Annapurna Region, Nepal' },
    features: ['High Passes', 'Diverse Terrain', 'Remote Villages', 'Thorong La Pass'],
    nearbyAttractions: ['Muktinath Temple', 'Manang', 'Tilicho Lake']
  },
  {
    name: 'Mardi Himal Trek',
    slug: 'mardi-himal',
    category: 'Adventure',
    region: 'Western',
    description: 'Mardi Himal is an off-the-beaten-path trek offering intimate views of Machhapuchhre (Fishtail Mountain) and the Annapurna range. The trail winds through dense rhododendron and bamboo forests before reaching high alpine ridges with panoramic Himalayan views.',
    shortDescription: 'Off-the-beaten-path trek with stunning views of Machhapuchhre and Annapurna.',
    images: ['https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=1200&q=80'],
    rating: 4.7, reviewCount: 189,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Apr', duration: '5-7 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [83.9470, 28.3930], address: 'Kaski, Nepal' },
    features: ['Fishtail Views', 'Rhododendron Forest', 'Less Crowded'],
    nearbyAttractions: ['Pokhara', 'Australian Camp', 'Annapurna Base Camp']
  },
  {
    name: 'Langtang Valley Trek',
    slug: 'langtang-valley',
    category: 'Adventure',
    region: 'Central',
    description: 'The Langtang Valley trek takes you through lush forests of oak and rhododendron, past cascading waterfalls, and into the stunning glacial valley below Langtang Lirung (7,227m). The Tamang heritage along the trail adds rich cultural depth to the journey.',
    shortDescription: 'Beautiful valley trek near Kathmandu with Tamang culture and glacial landscapes.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.6, reviewCount: 198,
    priceRange: 'Rs Rs', bestSeason: 'Mar-May, Oct-Nov', duration: '7-10 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [85.6138, 28.2092], address: 'Rasuwa, Nepal' },
    features: ['Glacial Valley', 'Tamang Heritage', 'Close to Kathmandu'],
    nearbyAttractions: ['Kyanjin Gompa', 'Gosaikunda Lake', 'Tserko Ri']
  },
  {
    name: 'Manaslu Circuit Trek',
    slug: 'manaslu-circuit',
    category: 'Adventure',
    region: 'Western',
    description: 'The Manaslu Circuit is a remote and unspoiled trek around the world\'s eighth highest mountain. Passing through diverse landscapes from subtropical to arctic, the trek crosses the Larkya La Pass at 5,160m and offers incredible cultural encounters with Tibetan-influenced communities.',
    shortDescription: 'Remote circuit around the world\'s 8th highest peak with Tibetan culture.',
    images: ['https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=1200&q=80'],
    rating: 4.8, reviewCount: 156,
    priceRange: 'Rs Rs Rs', bestSeason: 'Mar-May, Sep-Nov', duration: '14-18 days', difficulty: 'Challenging',
    location: { type: 'Point', coordinates: [84.5597, 28.5500], address: 'Gorkha, Nepal' },
    features: ['Remote Trail', 'Larkya La Pass', 'Tibetan Culture', 'Pristine Wilderness'],
    nearbyAttractions: ['Samagaun', 'Birendra Lake', 'Larkya La Pass']
  },
  {
    name: 'Upper Mustang Trek',
    slug: 'upper-mustang',
    category: 'Adventure',
    region: 'Western',
    description: 'Upper Mustang, the former Kingdom of Lo, is a restricted area that preserves ancient Tibetan Buddhist culture. The landscape resembles the Tibetan Plateau with dramatic red and orange cliffs, ancient cave dwellings, and the walled city of Lo Manthang.',
    shortDescription: 'Forbidden kingdom with Tibetan culture, cave cities, and desert landscapes.',
    images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80'],
    rating: 4.9, reviewCount: 134,
    priceRange: 'Rs Rs Rs', bestSeason: 'Jun-Sep', duration: '10-14 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [83.9570, 29.1800], address: 'Mustang, Nepal' },
    features: ['Ancient Kingdom', 'Desert Landscape', 'Cave Dwellings', 'Restricted Area'],
    nearbyAttractions: ['Lo Manthang', 'Choser Caves', 'Muktinath']
  },
  {
    name: 'Gokyo Lakes Trek',
    slug: 'gokyo-lakes',
    category: 'Adventure',
    region: 'Eastern',
    description: 'The Gokyo Lakes trek leads to a series of stunning turquoise glacial lakes in the Everest region. Climbing Gokyo Ri (5,357m) offers one of the best panoramic views of Everest, Lhotse, Makalu, and Cho Oyu from a single viewpoint.',
    shortDescription: 'Turquoise glacial lakes with panoramic Everest views from Gokyo Ri.',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    rating: 4.8, reviewCount: 210,
    priceRange: 'Rs Rs Rs', bestSeason: 'Mar-May, Oct-Nov', duration: '12-14 days', difficulty: 'Challenging',
    location: { type: 'Point', coordinates: [86.6813, 27.9614], address: 'Solukhumbu, Nepal' },
    features: ['Glacial Lakes', 'Gokyo Ri Summit', '4 Eight-thousanders View'],
    nearbyAttractions: ['Everest Base Camp', 'Cho La Pass', 'Renjo La Pass']
  },
  {
    name: 'Annapurna Base Camp',
    slug: 'annapurna-base-camp',
    category: 'Adventure',
    region: 'Western',
    description: 'The Annapurna Base Camp trek takes you into the heart of the Annapurna Sanctuary, a natural amphitheater surrounded by towering peaks. The base camp sits at 4,130m with 360-degree views of Annapurna I, Machhapuchhre, and Hiunchuli.',
    shortDescription: 'Trek into the Annapurna Sanctuary surrounded by towering Himalayan peaks.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.7, reviewCount: 312,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Apr', duration: '7-12 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [83.8770, 28.5310], address: 'Kaski, Nepal' },
    features: ['Mountain Amphitheater', '360° Views', 'Hot Springs at Jhinu'],
    nearbyAttractions: ['Ghorepani', 'Poon Hill', 'Machhapuchhre Base Camp']
  },
  {
    name: 'Poon Hill Trek',
    slug: 'poon-hill',
    category: 'Adventure',
    region: 'Western',
    description: 'Poon Hill is one of the easiest and most rewarding short treks in Nepal. The sunrise from Poon Hill (3,210m) reveals a stunning panorama of Dhaulagiri, Annapurna South, Machhapuchhre, and Manaslu. The trail passes through charming Gurung and Magar villages.',
    shortDescription: 'Easy short trek with spectacular sunrise panorama of the Himalayas.',
    images: ['https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=1200&q=80'],
    rating: 4.6, reviewCount: 445,
    priceRange: 'Rs', bestSeason: 'Oct-May', duration: '4-5 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.6995, 28.3995], address: 'Myagdi, Nepal' },
    features: ['Sunrise Viewpoint', 'Gurung Villages', 'Short Trek', 'Rhododendron Forest'],
    nearbyAttractions: ['Ghorepani', 'Tadapani', 'Ghandruk']
  },
  {
    name: 'Kanchenjunga Base Camp',
    slug: 'kanchenjunga-base-camp',
    category: 'Adventure',
    region: 'Eastern',
    description: 'The Kanchenjunga trek leads to the base of the world\'s third highest peak in far-eastern Nepal. This remote trail passes through pristine forests, crosses high passes, and offers encounters with diverse ethnic communities including Limbu and Rai peoples.',
    shortDescription: 'Remote trek to the world\'s third highest peak in far-eastern Nepal.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.7, reviewCount: 89,
    priceRange: 'Rs Rs Rs', bestSeason: 'Mar-May, Oct-Nov', duration: '18-22 days', difficulty: 'Expert',
    location: { type: 'Point', coordinates: [88.1489, 27.7025], address: 'Taplejung, Nepal' },
    features: ['Remote Wilderness', 'Third Highest Peak', 'Diverse Ethnic Groups'],
    nearbyAttractions: ['Yalung Glacier', 'Ghunsa Valley', 'Ramche']
  },
  {
    name: 'Tilicho Lake',
    slug: 'tilicho-lake',
    category: 'Adventure',
    region: 'Western',
    description: 'Tilicho Lake, at 4,919m, is one of the highest lakes in the world. Set against the massive north face of the Tilicho Peak and the Great Barrier wall, the deep blue lake in a barren landscape creates an otherworldly scene.',
    shortDescription: 'One of the world\'s highest lakes at 4,919m with stunning mountain backdrop.',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    rating: 4.8, reviewCount: 167,
    priceRange: 'Rs Rs', bestSeason: 'Sep-Nov', duration: '10-12 days', difficulty: 'Challenging',
    location: { type: 'Point', coordinates: [83.8500, 28.6833], address: 'Manang, Nepal' },
    features: ['Highest Lake', 'Barren Landscape', 'Great Barrier Wall'],
    nearbyAttractions: ['Manang Village', 'Annapurna Circuit', 'Ice Lake']
  },
  {
    name: 'Rara Lake Trek',
    slug: 'rara-lake',
    category: 'Adventure',
    region: 'Far-Western',
    description: 'Rara Lake is Nepal\'s largest and deepest lake, set at 2,990m in the remote far-western hills. The crystal-clear waters change color with the seasons, surrounded by dense forests of blue pine, spruce, and juniper. It is one of Nepal\'s most pristine destinations.',
    shortDescription: 'Nepal\'s largest lake in the pristine far-western wilderness.',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    rating: 4.7, reviewCount: 98,
    priceRange: 'Rs Rs', bestSeason: 'Sep-Nov, Mar-May', duration: '8-10 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [82.0833, 29.5167], address: 'Mugu, Nepal' },
    features: ['Largest Lake', 'Remote Wilderness', 'Pine Forests', 'Pristine Waters'],
    nearbyAttractions: ['Rara National Park', 'Murma Top', 'Gamgadhi']
  },
  {
    name: 'Bungee Jumping at The Last Resort',
    slug: 'bungee-jumping-last-resort',
    category: 'Adventure',
    region: 'Central',
    description: 'The Last Resort offers one of the longest bungee jumps in the world at 160m, plunging into the Bhote Koshi River gorge. Located just 3 hours from Kathmandu, it also offers canyoning, rafting, and canyon swinging in a stunning river valley.',
    shortDescription: 'One of the world\'s longest bungee jumps at 160m into the Bhote Koshi gorge.',
    images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    rating: 4.5, reviewCount: 234,
    priceRange: 'Rs Rs', bestSeason: 'Oct-May', duration: '1-2 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [85.9789, 27.8906], address: 'Sindhupalchok, Nepal' },
    features: ['Bungee Jump', 'Canyon Swing', 'River Rafting', 'Canyoning'],
    nearbyAttractions: ['Bhote Koshi River', 'Tatopani Hot Springs']
  },
  {
    name: 'Paragliding in Pokhara',
    slug: 'paragliding-pokhara',
    category: 'Adventure',
    region: 'Western',
    description: 'Pokhara is one of the best paragliding destinations in the world. Launching from Sarangkot at 1,592m, you soar over Phewa Lake with the entire Annapurna range as your backdrop. Tandem flights with experienced pilots make it accessible to everyone.',
    shortDescription: 'World-class paragliding over Phewa Lake with Annapurna range views.',
    images: ['https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=1200&q=80'],
    rating: 4.8, reviewCount: 567,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Apr', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.9536, 28.2440], address: 'Sarangkot, Pokhara, Nepal' },
    features: ['Tandem Flights', 'Annapurna Views', 'Phewa Lake', 'Thermal Soaring'],
    nearbyAttractions: ['Sarangkot Sunrise', 'Phewa Lake', 'World Peace Pagoda']
  },
  {
    name: 'White Water Rafting - Trisuli River',
    slug: 'rafting-trisuli',
    category: 'Adventure',
    region: 'Central',
    description: 'The Trisuli River offers exciting Class III-IV rapids perfect for both beginners and experienced rafters. The scenic route from Kathmandu to Chitwan passes through lush valleys with views of terraced hillsides and traditional villages.',
    shortDescription: 'Exciting Class III-IV rapids on the scenic Trisuli River.',
    images: ['https://images.unsplash.com/photo-1530866495561-507c83fa9e47?w=1200&q=80'],
    rating: 4.5, reviewCount: 289,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Dec, Mar-May', duration: '1-2 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [84.9167, 27.7500], address: 'Dhading, Nepal' },
    features: ['Class III-IV Rapids', 'Scenic Valley', 'Camping', 'Beginner Friendly'],
    nearbyAttractions: ['Chitwan National Park', 'Manakamana Temple', 'Devighat']
  },

  // === NATURE (12) ===
  {
    name: 'Pokhara',
    slug: 'pokhara',
    category: 'Nature',
    region: 'Western',
    description: 'Pokhara is the gateway to the Annapurna region and one of Nepal\'s most beloved destinations. Sitting on the shores of the serene Phewa Lake with stunning views of Machhapuchhre and the Annapurna range, Pokhara offers a perfect blend of natural beauty, adventure activities, and relaxation.',
    shortDescription: 'Lakeside paradise with stunning Annapurna views and adventure activities.',
    images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    rating: 4.8, reviewCount: 528,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Apr', duration: '3-5 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.9856, 28.2096], address: 'Kaski, Nepal' },
    features: ['Phewa Lake', 'Mountain Views', 'Paragliding', 'Caves', 'Boating'],
    nearbyAttractions: ['Phewa Lake', 'World Peace Pagoda', 'Devi\'s Fall', 'Sarangkot']
  },
  {
    name: 'Chitwan National Park',
    slug: 'chitwan',
    category: 'Nature',
    region: 'Central',
    description: 'Chitwan National Park is Nepal\'s first national park and a UNESCO World Heritage Site. Covering 952 sq km of subtropical lowlands, it is home to the endangered one-horned rhinoceros, Bengal tiger, gharial crocodile, and over 500 bird species.',
    shortDescription: 'UNESCO heritage wildlife sanctuary with rhinos, tigers, and jungle safaris.',
    images: ['https://images.unsplash.com/photo-1535338454770-7a0d5d532129?w=1200&q=80'],
    rating: 4.6, reviewCount: 445,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Mar', duration: '2-3 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [84.3333, 27.5000], address: 'Chitwan, Nepal' },
    features: ['Wildlife Safari', 'Bird Watching', 'Tharu Culture', 'Elephant Bathing'],
    nearbyAttractions: ['Sauraha', 'Rapti River', 'Elephant Breeding Center', 'Bis Hajaar Taal']
  },
  {
    name: 'Bardia National Park',
    slug: 'bardia-national-park',
    category: 'Nature',
    region: 'Far-Western',
    description: 'Bardia National Park is Nepal\'s largest national park in the Terai and offers a wilder, less touristy alternative to Chitwan. It has one of the highest densities of Bengal tigers in Nepal along with wild elephants, gharial crocodiles, and the endangered Gangetic dolphin.',
    shortDescription: 'Wild and untouched jungle with the highest tiger density in Nepal.',
    images: ['https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=1200&q=80'],
    rating: 4.7, reviewCount: 178,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Apr', duration: '3-5 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [81.5000, 28.3833], address: 'Bardia, Nepal' },
    features: ['Tiger Tracking', 'Wild Elephants', 'Gangetic Dolphins', 'Rafting'],
    nearbyAttractions: ['Karnali River', 'Tharu Villages', 'Babai Valley']
  },
  {
    name: 'Phewa Lake',
    slug: 'phewa-lake',
    category: 'Nature',
    region: 'Western',
    description: 'Phewa Lake is the second largest lake in Nepal and the centerpiece of Pokhara. Its calm waters perfectly reflect Machhapuchhre and the Annapurna range. Visitors can rent colorful rowboats, visit the Tal Barahi Temple on the island, or simply enjoy the lakeside cafes.',
    shortDescription: 'Serene lake reflecting the Annapurna range, heart of Pokhara.',
    images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    rating: 4.6, reviewCount: 890,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.9480, 28.2149], address: 'Pokhara, Nepal' },
    features: ['Boating', 'Reflection Views', 'Tal Barahi Temple', 'Lakeside Restaurants'],
    nearbyAttractions: ['World Peace Pagoda', 'Devi\'s Fall', 'Pokhara Lakeside']
  },
  {
    name: 'Gosaikunda Lake',
    slug: 'gosaikunda-lake',
    category: 'Nature',
    region: 'Central',
    description: 'Gosaikunda is a sacred alpine freshwater lake at 4,380m in the Langtang region. According to Hindu mythology, Lord Shiva created the lake by striking a rock with his trident. Thousands of pilgrims visit during Janai Purnima festival.',
    shortDescription: 'Sacred alpine lake at 4,380m with mythological significance.',
    images: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80'],
    rating: 4.6, reviewCount: 145,
    priceRange: 'Rs Rs', bestSeason: 'Mar-May, Aug-Oct', duration: '5-7 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [85.4167, 28.0833], address: 'Rasuwa, Nepal' },
    features: ['Sacred Lake', 'Alpine Setting', 'Pilgrimage Site', 'Mountain Views'],
    nearbyAttractions: ['Langtang Valley', 'Laurebina Pass', 'Helambu']
  },
  {
    name: 'Nagarkot',
    slug: 'nagarkot',
    category: 'Nature',
    region: 'Central',
    description: 'Nagarkot is the closest hill station from Kathmandu offering panoramic views of the Himalayan range including Everest on clear days. Famous for its spectacular sunrise and sunset, it offers views of eight mountain ranges from Annapurna to Everest.',
    shortDescription: 'Hill station near Kathmandu with panoramic sunrise views of 8 Himalayan ranges.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.4, reviewCount: 567,
    priceRange: 'Rs', bestSeason: 'Oct-Mar', duration: '1-2 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.5167, 27.7167], address: 'Bhaktapur, Nepal' },
    features: ['Sunrise Views', 'Mountain Panorama', 'Short Trip from Kathmandu'],
    nearbyAttractions: ['Bhaktapur Durbar Square', 'Changu Narayan', 'Dhulikhel']
  },
  {
    name: 'Devi\'s Fall (Patale Chhango)',
    slug: 'devis-fall',
    category: 'Nature',
    region: 'Western',
    description: 'Devi\'s Fall is a stunning waterfall where the Pardi Khola stream disappears underground into a deep gorge. Named after a Swiss tourist who fell into the falls in 1961, it is one of Pokhara\'s most visited natural attractions.',
    shortDescription: 'Dramatic waterfall that disappears underground into a mysterious gorge.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1200&q=80'],
    rating: 4.2, reviewCount: 678,
    priceRange: 'Rs', bestSeason: 'Jul-Sep', duration: '1-2 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.9535, 28.1806], address: 'Pokhara, Nepal' },
    features: ['Waterfall', 'Underground River', 'Easy Access'],
    nearbyAttractions: ['Gupteshwor Cave', 'International Mountain Museum', 'Phewa Lake']
  },
  {
    name: 'Ilam Tea Gardens',
    slug: 'ilam-tea-gardens',
    category: 'Nature',
    region: 'Eastern',
    description: 'Ilam district in eastern Nepal is famous for its vast rolling tea gardens, often compared to Darjeeling. The emerald green tea plantations set against misty hills create a picturesque landscape. Visitors can tour tea factories and sample fresh orthodox tea.',
    shortDescription: 'Rolling emerald tea gardens of eastern Nepal with misty hill landscapes.',
    images: ['https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=1200&q=80'],
    rating: 4.3, reviewCount: 134,
    priceRange: 'Rs', bestSeason: 'Mar-May, Oct-Nov', duration: '2-3 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [87.9244, 26.9094], address: 'Ilam, Nepal' },
    features: ['Tea Plantations', 'Factory Tours', 'Misty Hills', 'Orthodox Tea'],
    nearbyAttractions: ['Mai Pokhari', 'Kanyam', 'Antu Danda']
  },
  {
    name: 'Begnas Lake',
    slug: 'begnas-lake',
    category: 'Nature',
    region: 'Western',
    description: 'Begnas Lake is a peaceful alternative to the busier Phewa Lake in Pokhara. Surrounded by forested hills and traditional villages, it offers serene boating, fishing, and swimming in crystal-clear waters with mountain reflections.',
    shortDescription: 'Peaceful lake near Pokhara with pristine waters and mountain reflections.',
    images: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=1200&q=80'],
    rating: 4.4, reviewCount: 178,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [84.0936, 28.1728], address: 'Kaski, Nepal' },
    features: ['Peaceful', 'Boating', 'Swimming', 'Less Crowded'],
    nearbyAttractions: ['Rupa Lake', 'Pokhara', 'Sundari Danda']
  },
  {
    name: 'Shivapuri Nagarjun National Park',
    slug: 'shivapuri-nagarjun',
    category: 'Nature',
    region: 'Central',
    description: 'Shivapuri Nagarjun National Park lies on the northern edge of Kathmandu Valley. It protects the watershed that supplies drinking water to the capital and offers excellent day hikes through dense forests with leopard, barking deer, and over 300 bird species.',
    shortDescription: 'Forested national park on Kathmandu\'s edge with excellent day hikes.',
    images: ['https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=1200&q=80'],
    rating: 4.3, reviewCount: 234,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '1 day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3753, 27.7984], address: 'Kathmandu, Nepal' },
    features: ['Day Hikes', 'Bird Watching', 'Forest Trails', 'Close to Kathmandu'],
    nearbyAttractions: ['Budhanilkantha', 'Nagi Gompa', 'Sundarijal']
  },

  // === RELIGIOUS (10) ===
  {
    name: 'Pashupatinath Temple',
    slug: 'pashupatinath',
    category: 'Religious',
    region: 'Central',
    description: 'Pashupatinath Temple is one of the most sacred Hindu temples in the world, dedicated to Lord Shiva. This UNESCO World Heritage Site on the banks of the Bagmati River features stunning pagoda-style architecture and is Nepal\'s most important cremation site.',
    shortDescription: 'Sacred Hindu temple and UNESCO World Heritage Site on the Bagmati River.',
    images: ['https://images.unsplash.com/photo-1568658176307-bfbd2873abda?w=1200&q=80'],
    rating: 4.7, reviewCount: 891,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3485, 27.7107], address: 'Kathmandu, Nepal' },
    features: ['Sacred Site', 'Pagoda Architecture', 'Cremation Ghats', 'Sadhus'],
    nearbyAttractions: ['Boudhanath Stupa', 'Kathmandu Durbar Square', 'Guhyeshwari Temple']
  },
  {
    name: 'Lumbini',
    slug: 'lumbini',
    category: 'Religious',
    region: 'Western',
    description: 'Lumbini is the birthplace of Lord Buddha (Siddhartha Gautama) and one of the most important pilgrimage sites in the world. The Sacred Garden contains the Maya Devi Temple marking the exact birth spot, the Ashoka Pillar from 249 BC, and monasteries built by Buddhist nations worldwide.',
    shortDescription: 'Birthplace of Buddha with sacred garden, Ashoka Pillar, and world monasteries.',
    images: ['https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=1200&q=80'],
    rating: 4.5, reviewCount: 356,
    priceRange: 'Rs', bestSeason: 'Oct-Mar', duration: '1-2 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.2762, 27.4833], address: 'Rupandehi, Nepal' },
    features: ['Buddhist Heritage', 'Maya Devi Temple', 'Ashoka Pillar', 'World Monasteries'],
    nearbyAttractions: ['Maya Devi Temple', 'Ashoka Pillar', 'Tilaurakot', 'Kapilvastu']
  },
  {
    name: 'Boudhanath Stupa',
    slug: 'boudhanath-stupa',
    category: 'Religious',
    region: 'Central',
    description: 'Boudhanath is one of the largest spherical stupas in the world and the holiest Tibetan Buddhist temple outside Tibet. The massive mandala-design stupa is surrounded by monasteries, prayer wheels, and the mesmerizing sound of Buddhist chants. UNESCO World Heritage Site.',
    shortDescription: 'One of the world\'s largest stupas and holiest Tibetan Buddhist site outside Tibet.',
    images: ['https://images.unsplash.com/photo-1568658176307-bfbd2873abda?w=1200&q=80'],
    rating: 4.7, reviewCount: 723,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3615, 27.7215], address: 'Kathmandu, Nepal' },
    features: ['Giant Stupa', 'Tibetan Culture', 'Prayer Wheels', 'Monasteries', 'Kora Walk'],
    nearbyAttractions: ['Pashupatinath', 'Kopan Monastery', 'Shechen Monastery']
  },
  {
    name: 'Swayambhunath (Monkey Temple)',
    slug: 'swayambhunath',
    category: 'Religious',
    region: 'Central',
    description: 'Swayambhunath, perched atop a hill in western Kathmandu, is an ancient religious complex with a gilded stupa featuring the all-seeing Buddha eyes. One of the oldest religious sites in Nepal (over 2,500 years), it offers panoramic views of the entire Kathmandu Valley.',
    shortDescription: 'Ancient hilltop stupa with Buddha eyes and panoramic Kathmandu Valley views.',
    images: ['https://images.unsplash.com/photo-1568658176307-bfbd2873abda?w=1200&q=80'],
    rating: 4.6, reviewCount: 892,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '2-3 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.2907, 27.7149], address: 'Kathmandu, Nepal' },
    features: ['Ancient Stupa', 'Buddha Eyes', 'Panoramic Views', 'Monkey Colony'],
    nearbyAttractions: ['Kathmandu Durbar Square', 'Garden of Dreams', 'Thamel']
  },
  {
    name: 'Muktinath Temple',
    slug: 'muktinath',
    category: 'Religious',
    region: 'Western',
    description: 'Muktinath at 3,710m is a sacred site for both Hindus and Buddhists. The Vishnu temple complex features 108 water spouts, an eternal flame fueled by natural gas behind a waterfall, and the Jwala Mai temple. It sits in the stunning Mustang landscape.',
    shortDescription: 'Sacred Hindu-Buddhist temple at 3,710m with 108 water spouts and eternal flame.',
    images: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80'],
    rating: 4.7, reviewCount: 234,
    priceRange: 'Rs Rs', bestSeason: 'Mar-Nov', duration: '1-2 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [83.8686, 28.8167], address: 'Mustang, Nepal' },
    features: ['108 Water Spouts', 'Eternal Flame', 'Hindu-Buddhist', 'High Altitude'],
    nearbyAttractions: ['Jomsom', 'Kagbeni', 'Upper Mustang']
  },
  {
    name: 'Changu Narayan Temple',
    slug: 'changu-narayan',
    category: 'Religious',
    region: 'Central',
    description: 'Changu Narayan is the oldest Hindu temple in the Kathmandu Valley, dating to the 4th century. This UNESCO World Heritage Site sits atop a hill surrounded by forests and features some of the finest examples of Licchavi-era stone, wood, and metal craftsmanship.',
    shortDescription: 'Oldest Hindu temple in Kathmandu Valley with exquisite Licchavi-era art.',
    images: ['https://images.unsplash.com/photo-1568658176307-bfbd2873abda?w=1200&q=80'],
    rating: 4.4, reviewCount: 267,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '2-3 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.4286, 27.7108], address: 'Bhaktapur, Nepal' },
    features: ['Oldest Temple', 'Licchavi Art', 'Hilltop Setting', 'Stone Inscriptions'],
    nearbyAttractions: ['Bhaktapur Durbar Square', 'Nagarkot', 'Dhulikhel']
  },
  {
    name: 'Manakamana Temple',
    slug: 'manakamana-temple',
    category: 'Religious',
    region: 'Central',
    description: 'Manakamana Temple is dedicated to the Hindu goddess Bhagwati, believed to fulfill wishes. Sitting atop a ridge at 1,302m, it is now accessible by Nepal\'s only cable car from Kurintar, offering stunning views of the Trisuli valley and Himalayan peaks.',
    shortDescription: 'Wish-fulfilling temple accessible by Nepal\'s cable car with valley views.',
    images: ['https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=1200&q=80'],
    rating: 4.3, reviewCount: 456,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [84.5861, 27.9500], address: 'Gorkha, Nepal' },
    features: ['Cable Car', 'Wish Fulfilling', 'Valley Views', 'Easy Access'],
    nearbyAttractions: ['Gorkha Durbar', 'Trisuli River', 'Bandipur']
  },
  {
    name: 'Janaki Temple',
    slug: 'janaki-temple',
    category: 'Religious',
    region: 'Central',
    description: 'Janaki Temple in Janakpur is a stunning Mughal-Rajput style temple dedicated to Goddess Sita, believed to be the site of her wedding to Lord Ram. The white marble structure with 60 rooms is one of Nepal\'s most architecturally unique religious buildings.',
    shortDescription: 'Stunning marble temple dedicated to Goddess Sita in Janakpur.',
    images: ['https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=1200&q=80'],
    rating: 4.4, reviewCount: 345,
    priceRange: 'Rs', bestSeason: 'Oct-Mar', duration: '1 day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.9260, 26.7288], address: 'Janakpur, Nepal' },
    features: ['Mughal Architecture', 'Sita\'s Wedding Site', 'White Marble', 'Mithila Culture'],
    nearbyAttractions: ['Ram Janaki Vivah Mandap', 'Dhanush Sagar', 'Mithila Art Galleries']
  },

  // === CULTURAL (10) ===
  {
    name: 'Kathmandu Durbar Square',
    slug: 'kathmandu-durbar-square',
    category: 'Cultural',
    region: 'Central',
    description: 'Kathmandu Durbar Square is the historic heart of the old city, home to the royal palace of the former Kathmandu Kingdom. This UNESCO World Heritage Site features dozens of temples, the Kumari Ghar (house of the living goddess), and intricate Newari wood carvings.',
    shortDescription: 'Historic royal palace square with temples and the living goddess Kumari.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.5, reviewCount: 789,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '3-4 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3076, 27.7047], address: 'Kathmandu, Nepal' },
    features: ['Kumari Ghar', 'Newari Architecture', 'Royal Palace', 'Temples'],
    nearbyAttractions: ['Thamel', 'Asan Bazaar', 'Swayambhunath']
  },
  {
    name: 'Bhaktapur Durbar Square',
    slug: 'bhaktapur-durbar-square',
    category: 'Cultural',
    region: 'Central',
    description: 'Bhaktapur Durbar Square is the best-preserved medieval city in Nepal. This UNESCO World Heritage Site features the 55-Window Palace, Nyatapola Temple (the tallest pagoda temple), the Golden Gate, and narrow lanes filled with pottery workshops and traditional Newari life.',
    shortDescription: 'Best-preserved medieval city with the iconic Nyatapola Temple and Golden Gate.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.7, reviewCount: 634,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '4-5 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.4282, 27.6719], address: 'Bhaktapur, Nepal' },
    features: ['55-Window Palace', 'Nyatapola Temple', 'Pottery Square', 'Juju Dhau (Yogurt)'],
    nearbyAttractions: ['Changu Narayan', 'Nagarkot', 'Thimi']
  },
  {
    name: 'Patan Durbar Square',
    slug: 'patan-durbar-square',
    category: 'Cultural',
    region: 'Central',
    description: 'Patan Durbar Square is known as the city of fine arts and is considered the oldest of the three Durbar Squares in the Kathmandu Valley. The square features the magnificent Krishna Mandir, the ancient Royal Palace, and the Patan Museum - one of the best museums in South Asia.',
    shortDescription: 'City of fine arts with Krishna Mandir and South Asia\'s finest museum.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.6, reviewCount: 567,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '3-4 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3256, 27.6728], address: 'Lalitpur, Nepal' },
    features: ['Krishna Mandir', 'Patan Museum', 'Metal Crafts', 'Newari Cuisine'],
    nearbyAttractions: ['Mahabouddha Temple', 'Golden Temple', 'Kathmandu Durbar Square']
  },
  {
    name: 'Bandipur',
    slug: 'bandipur',
    category: 'Cultural',
    region: 'Central',
    description: 'Bandipur is a beautifully preserved Newari hilltop settlement perched on a ridge between Kathmandu and Pokhara. Its car-free main bazaar, traditional architecture, and panoramic Himalayan views make it one of Nepal\'s most charming cultural destinations.',
    shortDescription: 'Charming preserved Newari hilltop town with car-free bazaar and Himalayan views.',
    images: ['https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=1200&q=80'],
    rating: 4.5, reviewCount: 234,
    priceRange: 'Rs', bestSeason: 'Oct-Apr', duration: '1-2 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [84.3992, 27.9333], address: 'Tanahu, Nepal' },
    features: ['Car-Free Town', 'Newari Heritage', 'Mountain Views', 'Traditional Bazaar'],
    nearbyAttractions: ['Siddha Gufa (Cave)', 'Manakamana Temple', 'Dumre']
  },
  {
    name: 'Tansen (Palpa)',
    slug: 'tansen-palpa',
    category: 'Cultural',
    region: 'Western',
    description: 'Tansen is a historic hill town that was once the capital of the Magar Palpa kingdom. Sitting at 1,343m, it features the Tansen Durbar (Rani Mahal is nearby), narrow cobblestone streets, and a traditional bazaar selling dhaka fabric, Nepal\'s national textile.',
    shortDescription: 'Historic Magar hill town with cobblestone streets and dhaka fabric bazaar.',
    images: ['https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=1200&q=80'],
    rating: 4.3, reviewCount: 145,
    priceRange: 'Rs', bestSeason: 'Oct-Mar', duration: '1-2 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.5456, 27.8667], address: 'Palpa, Nepal' },
    features: ['Dhaka Fabric', 'Historic Town', 'Mountain Views', 'Rani Mahal'],
    nearbyAttractions: ['Rani Mahal', 'Srinagar Hill', 'Ridi Temple']
  },
  {
    name: 'Ghandruk Village',
    slug: 'ghandruk',
    category: 'Cultural',
    region: 'Western',
    description: 'Ghandruk is one of the largest Gurung villages in Nepal, set on a hillside at 1,940m with spectacular views of Annapurna South and Machhapuchhre. The village features a Gurung museum, traditional stone houses, and is a major stop on Annapurna treks.',
    shortDescription: 'Traditional Gurung village with stunning Annapurna and Machhapuchhre views.',
    images: ['https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=1200&q=80'],
    rating: 4.5, reviewCount: 289,
    priceRange: 'Rs', bestSeason: 'Oct-Apr', duration: '2-3 days', difficulty: 'Moderate',
    location: { type: 'Point', coordinates: [83.8078, 28.3753], address: 'Kaski, Nepal' },
    features: ['Gurung Culture', 'Mountain Views', 'Traditional Architecture', 'Gurung Museum'],
    nearbyAttractions: ['Annapurna Base Camp', 'Tadapani', 'Poon Hill']
  },
  {
    name: 'Garden of Dreams',
    slug: 'garden-of-dreams',
    category: 'Cultural',
    region: 'Central',
    description: 'The Garden of Dreams is a neo-classical European-style garden built in the 1920s, hidden in the heart of bustling Thamel. Restored by the Austrian government, it features ornamental pavilions, pergolas, ponds, and is a peaceful oasis in the midst of Kathmandu chaos.',
    shortDescription: 'Neo-classical European garden oasis hidden in the heart of Thamel, Kathmandu.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.3, reviewCount: 456,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '1-2 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3145, 27.7144], address: 'Thamel, Kathmandu, Nepal' },
    features: ['European Garden', 'Peaceful Oasis', 'Pavilions', 'Ponds'],
    nearbyAttractions: ['Thamel', 'Kathmandu Durbar Square', 'Narayanhiti Palace Museum']
  },
  {
    name: 'Nuwakot Durbar',
    slug: 'nuwakot-durbar',
    category: 'Cultural',
    region: 'Central',
    description: 'Nuwakot Durbar is a 7-story palace built by Prithvi Narayan Shah in the 18th century, serving as the strategic base for his unification of Nepal. The well-preserved fortress offers panoramic views of the surrounding valleys and Ganesh Himal range.',
    shortDescription: 'Historic 18th-century fortress of Nepal\'s unifier with mountain views.',
    images: ['https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=1200&q=80'],
    rating: 4.2, reviewCount: 134,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '1 day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.1647, 27.9103], address: 'Nuwakot, Nepal' },
    features: ['Historic Fortress', '7-Story Palace', 'Mountain Views', 'Unification History'],
    nearbyAttractions: ['Trisuli Bazaar', 'Kakani', 'Langtang Gateway']
  },

  // === URBAN (5) ===
  {
    name: 'Thamel',
    slug: 'thamel',
    category: 'Urban',
    region: 'Central',
    description: 'Thamel is the vibrant tourist hub of Kathmandu, packed with narrow lanes filled with trekking gear shops, bookstores, restaurants serving cuisine from around the world, rooftop bars, and budget-friendly hotels. It is the starting point for most Nepal adventures.',
    shortDescription: 'Kathmandu\'s vibrant tourist hub with shops, restaurants, and nightlife.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.2, reviewCount: 1234,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Ongoing', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3115, 27.7156], address: 'Thamel, Kathmandu, Nepal' },
    features: ['Shopping', 'Restaurants', 'Nightlife', 'Trekking Gear', 'Budget Hotels'],
    nearbyAttractions: ['Garden of Dreams', 'Kathmandu Durbar Square', 'Swayambhunath']
  },
  {
    name: 'Pokhara Lakeside',
    slug: 'pokhara-lakeside',
    category: 'Urban',
    region: 'Western',
    description: 'Lakeside is the tourist district of Pokhara, stretching along the eastern shore of Phewa Lake. The laid-back strip is lined with restaurants, cafes, souvenir shops, and travel agencies, all with views of the Annapurna range reflected in the lake.',
    shortDescription: 'Laid-back tourist district along Phewa Lake with mountain-view cafes.',
    images: ['https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80'],
    rating: 4.4, reviewCount: 890,
    priceRange: 'Rs Rs', bestSeason: 'Year-round', duration: 'Ongoing', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [83.9580, 28.2080], address: 'Lakeside, Pokhara, Nepal' },
    features: ['Lake Views', 'Restaurants', 'Shopping', 'Relaxed Atmosphere'],
    nearbyAttractions: ['Phewa Lake', 'World Peace Pagoda', 'Devi\'s Fall']
  },
  {
    name: 'Asan Bazaar',
    slug: 'asan-bazaar',
    category: 'Urban',
    region: 'Central',
    description: 'Asan Bazaar is one of the oldest and most vibrant market squares in Kathmandu. At the intersection of six streets, this chaotic and colorful market sells everything from spices, grains, and vegetables to religious offerings, textiles, and traditional medicines.',
    shortDescription: 'Ancient vibrant market at the crossroads of six streets in old Kathmandu.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.3, reviewCount: 456,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: '2-3 hours', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.3120, 27.7070], address: 'Asan, Kathmandu, Nepal' },
    features: ['Traditional Market', 'Spices', 'Local Life', 'Street Food', 'Temples'],
    nearbyAttractions: ['Indra Chowk', 'Kathmandu Durbar Square', 'Thamel']
  },
  {
    name: 'Dhulikhel',
    slug: 'dhulikhel',
    category: 'Urban',
    region: 'Central',
    description: 'Dhulikhel is a charming Newari town east of Kathmandu known for its stunning mountain views and traditional architecture. Popular for weekend getaways, it offers boutique resorts, organic farms, and panoramic views from Langtang to Everest.',
    shortDescription: 'Charming Newari town with mountain views and boutique resorts near Kathmandu.',
    images: ['https://images.unsplash.com/photo-1506905923166-8a59b4b553c0?w=1200&q=80'],
    rating: 4.4, reviewCount: 312,
    priceRange: 'Rs Rs', bestSeason: 'Oct-Mar', duration: '1-2 days', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.5567, 27.6200], address: 'Kavrepalanchok, Nepal' },
    features: ['Mountain Panorama', 'Newari Town', 'Weekend Getaway', 'Organic Farms'],
    nearbyAttractions: ['Namobuddha', 'Panauti', 'Bhaktapur']
  },
  {
    name: 'Kirtipur',
    slug: 'kirtipur',
    category: 'Urban',
    region: 'Central',
    description: 'Kirtipur is an ancient Newari hilltop city on the southwestern rim of the Kathmandu Valley. Once an independent kingdom, it was the last to fall to Prithvi Narayan Shah. Today it offers authentic Newari culture, temples, and the famous Newari feast (Newari Bhoj).',
    shortDescription: 'Ancient hilltop Newari city with authentic culture and traditional feasts.',
    images: ['https://images.unsplash.com/photo-1565073182887-6bcefbe225b1?w=1200&q=80'],
    rating: 4.2, reviewCount: 189,
    priceRange: 'Rs', bestSeason: 'Year-round', duration: 'Half day', difficulty: 'Easy',
    location: { type: 'Point', coordinates: [85.2781, 27.6789], address: 'Kirtipur, Nepal' },
    features: ['Ancient City', 'Newari Cuisine', 'Hilltop Views', 'Temples'],
    nearbyAttractions: ['Chobar Gorge', 'Tribhuvan University', 'Patan']
  }
];

async function seedDestinations() {
  try {
    let created = 0;
    let skipped = 0;
    
    for (const destData of demoDestinations) {
      const existing = await Destination.findOne({ slug: destData.slug });
      if (existing) {
        console.log(`⚠️  Skipped ${destData.slug} - already exists`);
        skipped++;
      } else {
        await Destination.create(destData);
        console.log(`✅ Created ${destData.slug}`);
        created++;
      }
    }
    console.log(`✅ Destinations seed complete: ${created} created, ${skipped} skipped`);
    return { created, skipped };
  } catch (error) {
    console.error('❌ Error seeding destinations:', error);
    throw error;
  }
}

module.exports = seedDestinations;
