import type { Destination, Guide, Review, BookingRequest, TouristProfile } from "./types"

// ============ DESTINATIONS ============
export const destinations: Destination[] = [
  {
    id: "1",
    name: "Everest Base Camp",
    slug: "everest-base-camp",
    category: "Adventure",
    region: "Eastern",
    description:
      "The Everest Base Camp trek is one of the most popular trekking routes in the Himalayas. Standing at the foot of the world's highest mountain, you'll experience breathtaking views, Sherpa culture, and the raw beauty of the Khumbu region. The trek passes through Namche Bazaar, Tengboche Monastery, and offers stunning views of Ama Dablam, Lhotse, and Nuptse.",
    shortDescription: "Trek to the base of the world's highest mountain through stunning Himalayan landscapes.",
    images: ["/images/everest.jpg"],
    rating: 4.9,
    reviewCount: 342,
    priceRange: "Rs Rs Rs",
    bestSeason: "Mar-May, Sep-Nov",
    duration: "12-14 days",
    difficulty: "Challenging",
    location: { coordinates: [86.8528, 28.0025], address: "Solukhumbu" },
    features: ["High Altitude", "Sherpa Culture", "Mountain Views"],
    nearbyAttractions: ["Namche Bazaar", "Tengboche Monastery", "Gokyo Lakes"],
  },
  {
    id: "2",
    name: "Pokhara",
    slug: "pokhara",
    category: "Nature",
    region: "Western",
    description:
      "Pokhara is the gateway to the Annapurna region and one of Nepal's most popular tourist destinations. The city sits on the shores of Phewa Lake with stunning views of the Annapurna and Dhaulagiri ranges. Activities include boating, paragliding, and visiting the World Peace Pagoda.",
    shortDescription: "Lakeside paradise with stunning Annapurna views and adventure activities.",
    images: ["/images/pokhara.jpg"],
    rating: 4.8,
    reviewCount: 528,
    priceRange: "Rs Rs",
    bestSeason: "Oct-Apr",
    duration: "3-5 days",
    difficulty: "Easy",
    location: { coordinates: [83.9856, 28.2096], address: "Kaski" },
    features: ["Lake Views", "Paragliding", "Peaceful"],
    nearbyAttractions: ["Phewa Lake", "World Peace Pagoda", "Davis Falls"],
  },
  {
    id: "3",
    name: "Pashupatinath Temple",
    slug: "pashupatinath",
    category: "Religious",
    region: "Central",
    description:
      "Pashupatinath Temple is one of the most sacred Hindu temples in the world, dedicated to Lord Shiva. Located on the banks of the Bagmati River, this UNESCO World Heritage Site features stunning pagoda-style architecture and is the site of Hindu cremation ceremonies.",
    shortDescription: "Sacred Hindu temple and UNESCO World Heritage Site on the Bagmati River.",
    images: ["/images/pashupatinath.jpg"],
    rating: 4.7,
    reviewCount: 891,
    priceRange: "Rs",
    bestSeason: "Year-round",
    duration: "Half day",
    difficulty: "Easy",
    location: { coordinates: [85.3485, 27.7107], address: "Kathmandu" },
    features: ["Sacred Site", "Architecture", "Cultural"],
    nearbyAttractions: ["Boudhanath Stupa", "Kathmandu Durbar Square"],
  },
  {
    id: "4",
    name: "Chitwan National Park",
    slug: "chitwan",
    category: "Nature",
    region: "Central",
    description:
      "Chitwan National Park is Nepal's first national park and a UNESCO World Heritage Site. Home to one-horned rhinoceros, Bengal tigers, and over 500 species of birds, it offers jungle safaris, canoe rides, and cultural experiences with the Tharu community.",
    shortDescription: "Nepal's premier wildlife sanctuary with rhinos, tigers, and jungle safaris.",
    images: ["/images/chitwan.jpg"],
    rating: 4.6,
    reviewCount: 445,
    priceRange: "Rs Rs",
    bestSeason: "Oct-Mar",
    duration: "2-3 days",
    difficulty: "Easy",
    location: { coordinates: [84.3333, 27.5], address: "Chitwan" },
    features: ["Wildlife Safari", "Bird Watching", "Tharu Culture"],
    nearbyAttractions: ["Sauraha", "Rapti River", "Elephant Breeding Center"],
  },
  {
    id: "5",
    name: "Annapurna Circuit",
    slug: "annapurna-circuit",
    category: "Adventure",
    region: "Western",
    description:
      "The Annapurna Circuit is one of the most diverse and spectacular trekking routes in the world. Circling the Annapurna massif, the trail passes through rice paddies, dense forests, high-altitude deserts, and crosses the Thorong La pass at 5,416m.",
    shortDescription: "Epic circuit trek around the Annapurna massif with diverse landscapes.",
    images: ["/images/annapurna.jpg"],
    rating: 4.8,
    reviewCount: 267,
    priceRange: "Rs Rs Rs",
    bestSeason: "Mar-May, Oct-Nov",
    duration: "15-20 days",
    difficulty: "Challenging",
    location: { coordinates: [83.8203, 28.5965], address: "Annapurna Region" },
    features: ["High Passes", "Diverse Terrain", "Remote Villages"],
    nearbyAttractions: ["Muktinath Temple", "Manang", "Tilicho Lake"],
  },
  {
    id: "6",
    name: "Lumbini",
    slug: "lumbini",
    category: "Religious",
    region: "Western",
    description:
      "Lumbini is the birthplace of Lord Buddha and one of the most important pilgrimage sites in the world. The Sacred Garden contains the Maya Devi Temple, the Ashoka Pillar, and numerous monasteries built by Buddhist communities from around the world.",
    shortDescription: "Birthplace of Buddha and a sacred pilgrimage site with world monasteries.",
    images: ["/images/lumbini.jpg"],
    rating: 4.5,
    reviewCount: 356,
    priceRange: "Rs",
    bestSeason: "Oct-Mar",
    duration: "1-2 days",
    difficulty: "Easy",
    location: { coordinates: [83.2762, 27.4833], address: "Rupandehi" },
    features: ["Buddhist Heritage", "Peaceful", "Monasteries"],
    nearbyAttractions: ["Maya Devi Temple", "Ashoka Pillar", "World Peace Pagoda"],
  },
]

// ============ GUIDES ============
export const guides: Guide[] = [
  {
    id: "1",
    name: "Pasang Sherpa",
    slug: "pasang-sherpa",
    avatar: "/images/everest.jpg",
    coverImage: "/images/annapurna.jpg",
    location: "Solukhumbu, Nepal",
    memberSince: "2018",
    rating: 4.9,
    reviewCount: 128,
    totalTrips: 150,
    experience: "8 Years",
    successRate: 98,
    responseTime: "<2 hours",
    languages: [
      { code: "EN", name: "English" },
      { code: "NP", name: "Nepali" },
      { code: "HI", name: "Hindi" },
    ],
    specializations: ["High Altitude Trekking", "Cultural Tours", "Photography Expeditions"],
    certifications: ["TAAN Licensed Guide", "Wilderness First Responder", "Mountain Safety Certified"],
    bio: "Experienced mountaineer with 8 years guiding across the Himalayas. Specialized in Everest Base Camp, Annapurna Circuit, and Langtang Valley treks. Passionate about sharing Nepal's culture and natural beauty with travelers from around the world.",
    pricePerDay: 3500,
    available: true,
    offerings: [
      "Customized itineraries",
      "Safety equipment provided",
      "Cultural insights",
      "Photography assistance",
      "Flexible scheduling",
    ],
  },
  {
    id: "2",
    name: "Mingma Tamang",
    slug: "mingma-tamang",
    avatar: "/images/pokhara.jpg",
    coverImage: "/images/pokhara.jpg",
    location: "Kathmandu Valley, Nepal",
    memberSince: "2019",
    rating: 4.8,
    reviewCount: 95,
    totalTrips: 120,
    experience: "6 Years",
    successRate: 97,
    responseTime: "<3 hours",
    languages: [
      { code: "EN", name: "English" },
      { code: "NP", name: "Nepali" },
      { code: "JP", name: "Japanese" },
    ],
    specializations: ["Cultural Tours", "Religious Sites", "Family-Friendly Hikes"],
    certifications: ["TAAN Licensed Guide", "Cultural Heritage Specialist"],
    bio: "Born and raised in the Kathmandu Valley, I specialize in cultural and heritage tours across Nepal. My deep knowledge of Hindu and Buddhist traditions allows me to offer authentic experiences at sacred sites.",
    pricePerDay: 3000,
    available: true,
    offerings: ["Temple tours", "Cultural immersion", "Family packages", "Heritage walks", "Local cuisine tours"],
  },
  {
    id: "3",
    name: "Dawa Lama",
    slug: "dawa-lama",
    avatar: "/images/chitwan.jpg",
    coverImage: "/images/chitwan.jpg",
    location: "Chitwan, Nepal",
    memberSince: "2017",
    rating: 4.7,
    reviewCount: 87,
    totalTrips: 200,
    experience: "10 Years",
    successRate: 99,
    responseTime: "<1 hour",
    languages: [
      { code: "EN", name: "English" },
      { code: "NP", name: "Nepali" },
      { code: "DE", name: "German" },
    ],
    specializations: ["Wildlife Safari", "Adventure Sports", "Bird Watching"],
    certifications: ["TAAN Licensed Guide", "Wildlife Conservation Certified", "First Aid Certified"],
    bio: "A wildlife enthusiast with over 10 years of experience in Chitwan National Park. I help travelers experience Nepal's incredible biodiversity, from one-horned rhinos to Bengal tigers.",
    pricePerDay: 2800,
    available: false,
    offerings: ["Jungle safaris", "Bird watching tours", "Canoe rides", "Tharu cultural evenings", "Nature walks"],
  },
]

// ============ REVIEWS ============
export const reviews: Review[] = [
  {
    id: "1",
    userId: "u1",
    userName: "Sarah Mitchell",
    userAvatar: "",
    userCountry: "USA",
    rating: 5,
    categoryRatings: { professionalism: 5, communication: 5, knowledge: 5, value: 5 },
    tripType: "Everest Base Camp Trek",
    date: "March 2026",
    text: "Found an amazing guide for my trek. Best experience in Nepal! Pasang was incredibly knowledgeable about the mountains and Sherpa culture. He made sure everyone was safe and comfortable throughout the entire journey.",
    photos: [],
    helpful: 24,
    guideResponse: "Thank you, Sarah! It was a pleasure guiding you through the Khumbu region.",
  },
  {
    id: "2",
    userId: "u2",
    userName: "James Wilson",
    userAvatar: "",
    userCountry: "UK",
    rating: 5,
    categoryRatings: { professionalism: 5, communication: 4, knowledge: 5, value: 5 },
    tripType: "Annapurna Circuit",
    date: "February 2026",
    text: "An unforgettable adventure! The guide's knowledge of the trail and local culture was exceptional. Every detail was taken care of, from permits to accommodation.",
    photos: [],
    helpful: 18,
  },
  {
    id: "3",
    userId: "u3",
    userName: "Yuki Tanaka",
    userAvatar: "",
    userCountry: "Japan",
    rating: 4,
    categoryRatings: { professionalism: 5, communication: 4, knowledge: 4, value: 4 },
    tripType: "Cultural Tour - Kathmandu Valley",
    date: "January 2026",
    text: "Great cultural experience! Learned so much about Nepal's history and traditions. The guide was very patient and explained everything in detail.",
    photos: [],
    helpful: 12,
  },
]

// ============ BOOKING REQUESTS ============
export const bookingRequests: BookingRequest[] = [
  {
    id: "b1",
    touristName: "Sarah Mitchell",
    touristAvatar: "",
    touristCountry: "USA",
    guideId: "1",
    guideName: "Pasang Sherpa",
    dates: { start: "2026-03-15", end: "2026-03-20" },
    destinations: ["Everest Base Camp", "Namche Bazaar"],
    packageType: "Full Day Adventure",
    addOns: ["Porter service"],
    groupSize: 2,
    specialRequirements: "Vegetarian meals preferred",
    totalPrice: 27500,
    offeredPrice: 25000,
    negotiationHistory: [{ price: 25000, by: 'tourist', message: 'Can we do 25k for 5 days?', at: '2026-03-01T10:00:00Z' }],
    status: "pending",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "b2",
    touristName: "James Wilson",
    touristAvatar: "",
    touristCountry: "UK",
    guideId: "1",
    guideName: "Pasang Sherpa",
    dates: { start: "2026-04-01", end: "2026-04-15" },
    destinations: ["Annapurna Circuit"],
    packageType: "Multi-Day Expedition",
    addOns: ["Porter service", "Photography package"],
    groupSize: 4,
    specialRequirements: "One member has mild altitude concerns",
    totalPrice: 95000,
    offeredPrice: 90000,
    agreedPrice: 95000,
    negotiationHistory: [
      { price: 90000, by: 'tourist', message: 'Offering 90k for the group', at: '2026-02-20T14:00:00Z' },
      { price: 95000, by: 'guide', message: 'Counter at 95k with photography included', at: '2026-02-20T15:00:00Z' },
    ],
    status: "confirmed",
    createdAt: "2026-02-20T14:00:00Z",
  },
  {
    id: "b3",
    touristName: "Yuki Tanaka",
    touristAvatar: "",
    touristCountry: "Japan",
    guideId: "2",
    guideName: "Mingma Tamang",
    dates: { start: "2026-03-10", end: "2026-03-12" },
    destinations: ["Pashupatinath Temple", "Boudhanath Stupa", "Kathmandu Durbar Square"],
    packageType: "Full Day Adventure",
    addOns: [],
    groupSize: 1,
    specialRequirements: "Japanese language preferred",
    totalPrice: 7000,
    offeredPrice: 7000,
    negotiationHistory: [{ price: 7000, by: 'tourist', message: '', at: '2026-03-02T08:00:00Z' }],
    status: "pending",
    createdAt: "2026-03-02T08:00:00Z",
  },
]

// ============ TOURIST PROFILE ============
export const currentTourist: TouristProfile = {
  id: "t1",
  name: "Alex Johnson",
  email: "alex@example.com",
  avatar: "",
  country: "Australia",
  phone: "+61 400 123 456",
  emergencyContact: { name: "Jane Johnson", phone: "+61 400 789 012" },
  preferences: {
    categories: ["Adventure", "Nature", "Cultural"],
    budget: "Mid-range",
    fitness: "High",
    travelStyle: "Solo",
    duration: "2 weeks",
  },
  stats: {
    placesVisited: 12,
    pinsCreated: 28,
    upcomingTrips: 1,
  },
}

// ============ TESTIMONIALS ============
export const testimonials = [
  {
    id: "t1",
    name: "Sarah M.",
    country: "United States",
    rating: 5,
    quote: "Found an amazing guide for my Everest Base Camp trek. Pasang made the journey unforgettable with his knowledge of Sherpa culture and incredible attention to safety.",
    tripType: "Everest Base Camp Trek",
    avatar: "",
  },
  {
    id: "t2",
    name: "Marco R.",
    country: "Italy",
    rating: 5,
    quote: "The personalized recommendations were spot on. Discovered hidden gems in the Annapurna region I would never have found on my own. Truly a game changer.",
    tripType: "Annapurna Circuit",
    avatar: "",
  },
  {
    id: "t3",
    name: "Aiko T.",
    country: "Japan",
    rating: 4,
    quote: "Booking a guide for the Kathmandu Valley cultural tour was seamless. The whole platform made planning my Nepal trip so much easier.",
    tripType: "Kathmandu Valley Tour",
    avatar: "",
  },
  {
    id: "t4",
    name: "Thomas K.",
    country: "Germany",
    rating: 5,
    quote: "The wildlife safari in Chitwan exceeded all expectations. Our guide's knowledge of the jungle and its wildlife was extraordinary.",
    tripType: "Chitwan Safari",
    avatar: "",
  },
]
